language: go
sudo: false

env:
  global:
    - GORACE="halt_on_error=1"
    - secure: "Q+bXWeD/7cOcyZniJOfhE2N2ilI+rZcEfElcDOtHykdkMAoIErszZMzhzeNtP77VQNeOGfszvyY22QIAP/l/G7UnmWfI8z9LBcM5UIu/8kIBdZe0f7Y5eK+YU9Gpls3VEoIjuh+bsWYW7lSgnDQMpnT+ugFb2tA5OCxYAoW00cRr1MNzt7IK16WK9g+wUvLAVOpxnVdbRi9qg9ma3ooLeIeX8fTj8FeYPZS26SvuQ8VBEgNOYeRGyMr8V18ZwnCE3ntPmd/XxWyPnqt21v3HCiSaOpLgYYmInAuPFRL5Kakq2GseXNYjNaq7DIutYgGROwvWDJZUXK7AuxwZzHKjCLmXL/rNYqTHUh7UpDozFT3vj7twz3IBRGA7c4tfI996+HD+4oK5jOkD5+IiA0Ve5pvcsCZU6cJk680ORChi+yPSJTYNU0kgqioX2Feb79cwlscpD9Bw4oXCVvj/z2QoF1R07gX6h3QLpOEsuM+c377z46vsdepIL3d9BiD0j5H0yPBKZg/Kv+eAb7POYDothRXbI73PpNssVFUnN5yPba5QzrZWJdaLGo9yQCxbggqQWBYqcUj6GgVUjMUZOVEYmfRD/jJjbxgPT2kX7gDW/WWomAYee9zSlKaTDUoT7dHj164m3KU+JtD0LZar4BXmP7tRU5f9RK7mA7Sp7WET97o="

  matrix:
    - TARGET=postgres
    - TARGET=mysql
    - TARGET=sqlite3

go:
  - 1.6.4
  - 1.7.4
  - tip

before_install:
  - if [[ $TARGET == *mysql* ]] ; then mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql; fi

  - mkdir $GOPATH/src/gopkg.in && mv $GOPATH/src/github.com/go-reform/reform $GOPATH/src/gopkg.in/reform.v1
  - cd $GOPATH/src/gopkg.in/reform.v1

install:
  - make download_deps
  - make install_deps

script:
  - make test $TARGET
  - make check

after_success:
  - goveralls -coverprofile=$TARGET.cover

notifications:
  webhooks:
    urls:
      - secure: "M5FL6dahsnY6TsU03QptqRoVriulkFPGLoKmbwLWAmPTk+h6SreMKIJHTmSba77snYVWR/gMLMNW01yMBrbV+ZmVgU6Sdp6yYlciA4cQcvIM7pwKuIfzeKhMCE2oeNVB3G2IHeu+FysbFXzI1JV9oU1I453aksyAPi4flf8eVUeMUa3nxWQt84MFC5RFn/pJ0G8lwUgAmHq56FjiOZ+5hF224s++CEEGGSclGZLH0/+T7SVH9sWSpyBuFtB6LZsl78JQ3mdxpFe95VAlpaB/PWdi7BXnZQ8XHgG1U1+1Z5at1uEmMmYjsQ5GzxaTEfjBRdC5AT6bRHjhW5wpI0tFKX77+1eexQXypuKyGIax7/7wFhKoEsU/9IUneqm17H9C5ZecF0xfvgTT4e2sHihm4qmYhQOFhGW+zlZdkp6rKzT17H0+g2q0IH3MJOKghyMO8l/YDy+wt2jdHggobfZLgcWLhyaHkUy0570jVUc+s+Zk/OOHr8kExvUcBuQeE38sQD6KEQoeeevXNlNtwrHvafjTfH1cUrc5JwFzP7go3VBEYxaHu+ctO7+DcUswOUsnTRiTQrp2FgNQP0TdlGgHgFV9cN5C+VcCwiB4NuU4ZM6J2TYmR6Wih4h/NooFKa8DiD++mqdyf6PhBn3tfHHtBFaLuE2GYMJ61MAv4kMNcBk="
